# Chaos Testing Docker Compose Configuration
# Optimized for resilience testing with resource limits and container isolation

services:
  server:
    container_name: chaos-starter-server
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8888:8080"
    env_file:
      - .env.example
    environment:
      # Database configuration for chaos testing
      - STARTER__DATABASE__HOST=postgres
      - STARTER__DATABASE__PORT=5432
      - STARTER__DATABASE__DATABASE=starter_db
      - DATABASE_URL=postgres://starter_user:starter_pass@postgres:5432/starter_db
      
      # Application configuration
      - STARTER__SERVER__HOST=0.0.0.0
      - STARTER__SERVER__PORT=8080
      
      # Chaos testing optimizations
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/starter", "health-check"]
      interval: 3s
      timeout: 2s
      start_period: 15s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    networks:
      - chaos-network
    labels:
      - "chaos.service=server"
      - "chaos.type=server"

  # Dynamic worker scaling for multi-worker chaos testing
  workers:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ["/app/starter", "worker"]
    env_file:
      - .env.example
    environment:
      # Database configuration (same as app)
      - STARTER__DATABASE__HOST=postgres
      - STARTER__DATABASE__PORT=5432
      - STARTER__DATABASE__DATABASE=starter_db
      - DATABASE_URL=postgres://starter_user:starter_pass@postgres:5432/starter_db
      
      # Worker configuration optimized for chaos testing
      - STARTER__WORKER__CONCURRENCY=2
      
      # API server connection for task type registration
      - API_BASE_URL=http://server:8080
      
      # Chaos testing optimizations
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/starter", "health-check"]
      interval: 3s
      timeout: 2s
      start_period: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.125'
      replicas: 1
    networks:
      - chaos-network
    labels:
      - "chaos.service=worker"
      - "chaos.type=worker"

  postgres:
    container_name: chaos-starter-postgres
    image: postgres:17-alpine
    env_file:
      - .env.example
    environment:
      - POSTGRES_DB=starter_db
      - POSTGRES_USER=starter_user
      - POSTGRES_PASSWORD=starter_pass
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - chaos_postgres_data:/var/lib/postgresql/data
      - ./starter/migrations:/docker-entrypoint-initdb.d/migrations:ro
    # No ports exposed - internal network communication only
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U starter_user -d starter_db"]
      interval: 2s
      timeout: 2s
      start_period: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.max=10000
      -c pg_stat_statements.track=all
      -c max_connections=50
      -c shared_buffers=64MB
      -c effective_cache_size=256MB
      -c work_mem=2MB
      -c maintenance_work_mem=32MB
      -c random_page_cost=1.1
      -c log_min_duration_statement=500
      -c log_checkpoints=on
      -c log_connections=on
      -c log_disconnections=on
      -c log_lock_waits=on
    networks:
      - chaos-network
    labels:
      - "chaos.service=database"
      - "chaos.type=postgres"

  # Network chaos container (for future network latency/partition testing)
  network-chaos:
    container_name: chaos-starter-network
    image: alpine:latest
    command: ["sleep", "infinity"]
    cap_add:
      - NET_ADMIN
    networks:
      - chaos-network
    labels:
      - "chaos.service=network"
      - "chaos.type=chaos-engineering"
    profiles:
      - network-chaos

volumes:
  chaos_postgres_data:
    driver: local

networks:
  chaos-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
    labels:
      - "chaos.network=true"